# This is a basic workflow to help you get started with Actions

name: ServiceNow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Apply Cahnges step
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: Installing dependecies
      run: npm install

    - name: Linting code
      run: npm run lint

    - name: Testing
      run: npm run test

    - name: Integration testing
      run: npm run integration

    - name: Compiling typescript
      run: npm run build